config/routes.rb
Ritly::Application.routes.draw do
  
  devise_for :users
  root "home#index" 
  resources :urls, :only => [:create, :new, :show, :index, :destroy]
  get '/:some_totally_random_value', to: 'urls#redirector', as: :redirect
  get '/:some_totally_random_value/preview', to: 'urls#preview', as: :preview

  

end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :link, :hash_code, presence: true 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :authenticate_user!

  def index
    @urls = Url.all
  end

  def new
    @url = Url.new
    @url.hash_code = SecureRandom.urlsafe_base64(8)
  end

  def create
    safe_url_params = params.require(:url).permit(:link, :hash_code)
    @url = Url.new safe_url_params
    if @url.save
      redirect_to url_path(@url)
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render '/home/index'
    end
  end

  def show
    @url = Url.find(params[:id])
    @full_path = "#{request.host_with_port}/#{@url.hash_code}"
  end

  def redirector
    @url = Url.find_by hash_code: params[:some_totally_random_value]
    if @url
      redirect_to @url.link
    else
      redirect_to root_path
    end
  end

  def preview
    @url = Url.find_by hash_code: params[:some_totally_random_value]
    unless @url
      redirect_to root_path
    end
  end

  def destroy
    @url = Url.find(params[:id])
    if @url.present?
      @url.destroy
    end
    flash[:notice] = "The following link has been un-shortened: '#{@url.link}'"
    redirect_to :action => 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/home/index.html.erb
<h1>Welcome to Ritly!</h1>
<p>Ritly is a URL-shortener, kind of like Bitly.</p>

<fieldset>

<%= link_to (radio_button_tag(:new, method: "get")), new_url_path %>
<%= label_tag(:new_code, "Have a URL you'd like to shorten?") %>
<%= link_to (radio_button_tag(:old, method: "get")), urls_path %>
<%= label_tag(:old_code, "I already shortened - let's find my existing Ritly URL!") %>
  
<div class="actions">
  <%= submit_tag("Let's go!") %>
</div>

</fieldset>

<h3 id="desination">TEST NAV</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign Up!", new_user_registration_path %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for @url do |f| %>
  
  <fieldset>

    <div class="field">
      <%= f.label :link %><br>
      <%= f.url_field :link %>
    </div>

    <div class="field">
      <%= f.label :hash_code %><br>
      <%= f.text_field :hash_code %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
    <div class="actions">
      <a href="#destination"> TEST</a>
    </div>

  </fieldset>
  
<% end %>

app/views/urls/index.html.erb
<h1>Here's our already-shortened links:</h1>

<% if @urls.empty? %>
<p>There are not any URLs currently in the system.</p>
<% end %>

<table>
	<tr>
		<th>Long URL</th>
		<th>Short URL (the "code")</th>
	</tr>

<% @urls.each do |url| %>
	<tr>
		<td><%= link_to url.link, url_path(url) %></td>
		<td><%= url.hash_code %></td>
		<td><%= link_to 'Destroy |', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td><%= link_to ' Preview', preview_path(url.hash_code), method: :get %></td>
	</tr>
<% end %>
</table>
<p></p>
<p><%= link_to "Home ", root_path %>
   <%= link_to " |  Make new Ritly", new_url_path %>
</p>

app/views/urls/new.html.erb
<h1>Enter the url to be shortened</h1>

<%= render :partial => 'form' %>
<%= link_to "Back", :back %>

app/views/urls/preview.html.erb
<h1>Code: <%= @url.hash_code %></h1>
<p>This code will take you to <%= @url.link %></p>
<%= link_to "Click Here", @url.link %> to continue

<%= link_to " | Back", :back %>

app/views/urls/show.html.erb
<h1><%= @url.hash_code%> is your code for <%= @url.link %></h1>

<p>Direct users to <%= @full_path %></p>
<p>
  <%= link_to "Link... ", @url.link %>
  <%= link_to " | Preview", preview_path(@url.hash_code) %>
  <%= link_to " | Back", :back %>
</p>